# Generated by Django 6.0.3 on 2026-03-27 10:46

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Категорія послуг',
                'verbose_name_plural': 'Категорії послуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва міста')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Заявка на консультацію',
                'verbose_name_plural': 'Заявки на консультацію',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто вильоту')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('transport', models.CharField(choices=[('air', 'літак'), ('bus', 'автобус')], max_length=50, verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Місто вильоту',
                'verbose_name_plural': 'Міста вильоту',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmenityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_popular_default', models.BooleanField(default=False, verbose_name='Популярна за замовчуванням')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_names', to='tours.amenitycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Можлива назва послуги',
                'verbose_name_plural': 'Можливі назви послуг',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна (для виділення)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='tours.amenitycategory', verbose_name='Категорія')),
                ('name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='tours.amenityname', verbose_name='Назва послуги')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва туру')),
                ('description', models.TextField(verbose_name='Опис')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Курорт/місто')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото туру')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Категорія (зірки)')),
                ('map_url', models.URLField(blank=True, help_text='Вставте посилання на Google Maps (iframe src)', max_length=500, verbose_name='Посилання на карту')),
                ('amenities', models.ManyToManyField(blank=True, related_name='tours', to='tours.amenity', verbose_name='Послуги та зручності')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Дата вильоту')),
                ('duration', models.PositiveSmallIntegerField(help_text='Кількість ночей', verbose_name='Тривалість (ночей)')),
                ('departure_city', models.CharField(default='Кишинів', max_length=100, verbose_name='Місто вильоту')),
                ('room_type', models.CharField(blank=True, default='Standard', max_length=100, verbose_name='Тип номера')),
                ('meal_type', models.CharField(choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Напівпансіон'), ('FB', 'Повний пансіон'), ('AI', 'Все включено')], default='AI', max_length=50, verbose_name='Харчування')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за тур (за двох)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Варіант ціни',
                'verbose_name_plural': 'Варіанти цін',
                'ordering': ['departure_date', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_gallery/', verbose_name='Додаткове фото')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оцініть тур від 1 до 5', verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
        migrations.CreateModel(
            name='PriceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('duration', models.PositiveSmallIntegerField(help_text='Кількість ночей', verbose_name='Тривалість (ночей)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Залиште порожнім, якщо немає пропозиції', max_digits=10, null=True, verbose_name='Ціна')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_calendar', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Календар цін',
                'verbose_name_plural': 'Календарі цін',
                'ordering': ['date', 'duration'],
                'unique_together': {('tour', 'date', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='tours.tour')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
