# Generated by Django 6.0.3 on 2026-05-19 14:39

import cloudinary.models
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Категорія послуг',
                'verbose_name_plural': 'Категорії послуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва міста')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('description', models.TextField(blank=True, verbose_name='Основна інформація про місто')),
                ('activities', models.TextField(blank=True, verbose_name='Чим зайнятися на курорті?')),
                ('sights', models.TextField(blank=True, verbose_name='Найцікавіші визначні місця')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Країна')),
                ('main_text', models.TextField(blank=True, verbose_name='Основна інформація')),
                ('why_text', models.TextField(blank=True, verbose_name='Чому варто вибрати?')),
                ('popular_resorts', models.TextField(blank=True, verbose_name='Популярні курорти')),
                ('activities', models.TextField(blank=True, verbose_name='Доступні види відпочинку')),
                ('sights', models.TextField(blank=True, verbose_name="Основні визначні пам'ятки")),
                ('useful_facts', models.TextField(blank=True, verbose_name='Корисні факти для туристів')),
            ],
            options={
                'verbose_name': 'Інформація про країну',
                'verbose_name_plural': 'Інформація про країни',
            },
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто вильоту')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('transport', models.CharField(choices=[('air', 'літак'), ('bus', 'автобус')], max_length=50, verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Місто вильоту',
                'verbose_name_plural': 'Міста вильоту',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Країна')),
                ('image', models.ImageField(upload_to='popular_destinations/', verbose_name='Фото для блоку')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Популярний напрямок',
                'verbose_name_plural': 'Популярні напрямки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopularHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50, verbose_name='ID готелю (hid)')),
                ('oid', models.CharField(max_length=100, verbose_name='ID пропозиції (oid)')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Назва готелю')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто/курорт')),
                ('rating', models.FloatField(default=8.0, verbose_name='Рейтинг (0-10)')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кількість відгуків')),
                ('price', models.IntegerField(verbose_name='Ціна за тур (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popular_hotels/', verbose_name='Фото готелю')),
                ('image_url', models.URLField(blank=True, verbose_name='URL фото (якщо немає завантаженого)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('od', models.CharField(blank=True, default='', max_length=20, verbose_name='Дата вильоту')),
                ('ol', models.CharField(blank=True, default='', max_length=10, verbose_name='Тривалість (ночей)')),
            ],
            options={
                'verbose_name': 'Популярний готель',
                'verbose_name_plural': 'Популярні готелі',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmenityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_popular_default', models.BooleanField(default=False, verbose_name='Популярна за замовчуванням')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_names', to='tours.amenitycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Можлива назва послуги',
                'verbose_name_plural': 'Можливі назви послуг',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна (для виділення)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='tours.amenitycategory', verbose_name='Категорія')),
                ('name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='tours.amenityname', verbose_name='Назва послуги')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('status', models.CharField(blank=True, default='new', max_length=20, verbose_name='Статус')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Заявка на консультацію',
                'verbose_name_plural': 'Заявки на консультацію',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Головне фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_gallery/', verbose_name='Додаткове фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.news')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('departure_city', models.CharField(default='Кишинів', max_length=100, verbose_name='Місто вильоту')),
                ('date', models.DateField(verbose_name='Дата вильоту')),
                ('duration', models.PositiveSmallIntegerField(default=7, help_text='Кількість ночей', verbose_name='Тривалість (ночей)')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Вкажіть ціну в гривнях (наприклад: 15000). Залиште порожнім, якщо немає пропозиції', max_digits=10, null=True, verbose_name='Ціна (грн)')),
            ],
            options={
                'verbose_name': 'Календар цін',
                'verbose_name_plural': 'Календарі цін',
                'ordering': ['date', 'duration'],
                'unique_together': {('country', 'departure_city', 'date', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва туру')),
                ('description', models.TextField(verbose_name='Опис')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('stars', models.IntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], default=None, help_text='Виберіть категорію готелю', null=True, verbose_name='Категорія готелю (зірки)')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото туру')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_url', models.URLField(blank=True, help_text='Вставте посилання на Google Maps (iframe src)', max_length=500, verbose_name='Посилання на карту')),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто виїзду')),
                ('transport', models.CharField(choices=[('air', 'літак'), ('bus', 'автобус')], default='air', max_length=10, verbose_name='Транспорт')),
                ('duration', models.PositiveSmallIntegerField(default=1, help_text='Кількість ночей', verbose_name='Тривалість (ночей)')),
                ('room_type', models.CharField(blank=True, default='Standard', max_length=100, verbose_name='Тип номера')),
                ('meal_type', models.CharField(choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Дворазове харчування'), ('FB', 'Триразове харчування'), ('AI', 'All Inclusive'), ('UAI', 'Ultra All Inclusive')], default='RO', max_length=3, verbose_name='Харчування')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярний готель')),
                ('amenities', models.ManyToManyField(blank=True, related_name='tours', to='tours.amenity', verbose_name='Послуги та зручності')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.city', verbose_name='Курорт/місто')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name="Ваше ім'я")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оцініть тур від 1 до 5', verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_gallery/', verbose_name='Додаткове фото')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_hid', models.CharField(db_index=True, max_length=50)),
                ('tour_oid', models.CharField(db_index=True, max_length=100)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tour_hid', 'tour_oid'], name='tours_tourv_tour_hi_58926a_idx'), models.Index(fields=['visited_at'], name='tours_tourv_visited_8be957_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50, verbose_name='ID готелю')),
                ('oid', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID туру')),
                ('guest_name', models.CharField(max_length=100, verbose_name="Ім'я гостя")),
                ('rating', models.IntegerField(help_text='Оцінка від 1 до 5', verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Відгук про готель',
                'verbose_name_plural': 'Відгуки про готелі',
                'ordering': ['-created_at'],
                'unique_together': {('hid', 'guest_name')},
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата вильоту')),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='Кількість ночей', null=True, verbose_name='Тривалість (ночей)')),
                ('departure_city', models.CharField(blank=True, default='Кишинів', max_length=100, verbose_name='Місто вильоту')),
                ('room_type', models.CharField(blank=True, default='Standard', max_length=100, verbose_name='Тип номера')),
                ('meal_type', models.CharField(blank=True, choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Напівпансіон'), ('FB', 'Повний пансіон'), ('AI', 'Все включено')], default='AI', max_length=50, verbose_name='Харчування')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Кількість дорослих')),
                ('infants', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 0-2 роки (без місця)')),
                ('children_2_3', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 2-3 роки')),
                ('children_4_10', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 4-10 років')),
                ('children_11_16', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 11-16 років')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за тур')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Варіант ціни',
                'verbose_name_plural': 'Варіанти цін',
                'ordering': ['departure_date', 'price'],
                'unique_together': {('tour', 'departure_date', 'duration', 'departure_city', 'room_type', 'meal_type', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
            },
        ),
        migrations.CreateModel(
            name='TourPriceByTourists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Кількість дорослих')),
                ('infants', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 0-2 роки (без місця)')),
                ('children_2_3', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 2-3 роки')),
                ('children_4_10', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 4-10 років')),
                ('children_11_16', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 11-16 років')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('is_default', models.BooleanField(default=False, verbose_name='Ціна за замовчуванням (якщо немає точної відповідності)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_by_tourists', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Ціна за складом туристів',
                'verbose_name_plural': 'Ціни за складом туристів',
                'unique_together': {('tour', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
            },
        ),
    ]
