# Generated by Django 6.0.3 on 2026-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecalendar',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Зніміть галочку, якщо на цю дату турів немає', verbose_name='Тури доступні'),
        ),
    ]
