# Generated by Django 6.0.3 on 2026-03-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_gallery/', verbose_name='Додаткове фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.news')),
            ],
        ),
    ]
