# Generated by Django 6.0.3 on 2026-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_news_author_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто виїзду'),
        ),
    ]
