# Generated by Django 6.0.3 on 2026-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_departure_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='transport',
            field=models.CharField(choices=[('air', 'літак'), ('bus', 'автобус')], default='air', max_length=10, verbose_name='Транспорт'),
        ),
    ]
