# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields

def copy_city_data(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    City = apps.get_model('tours', 'City')
    for tour in Tour.objects.all():
        if tour.city and isinstance(tour.city, str):
            # Знайти або створити запис у City
            city_obj, created = City.objects.get_or_create(
                name=tour.city.strip(),
                country=tour.country
            )
            tour.city_new = city_obj
            tour.save()

def reverse_copy(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    for tour in Tour.objects.all():
        if tour.city_new:
            tour.city = tour.city_new.name
            tour.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_transport'),
    ]

    operations = [
        # 1. Додати нове поле city_new як ForeignKey
        migrations.AddField(
            model_name='tour',
            name='city_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='tours.city',
                verbose_name='Курорт/місто (тимчасово)'
            ),
        ),
        # 2. Перенести дані зі старого текстового поля city в city_new
        migrations.RunPython(copy_city_data, reverse_copy),
        # 3. Видалити старе текстове поле city
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        # 4. Перейменувати city_new в city (виправлено: old_name / new_name)
        migrations.RenameField(
            model_name='tour',
            old_name='city_new',
            new_name='city',
        ),
        # 5. Перетворити city на ChainedForeignKey
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field='country',
                chained_model_field='country',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='tours.city',
                verbose_name='Курорт/місто'
            ),
        ),
    ]