# Generated by Django 6.0.3 on 2026-04-01 12:37

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_convert_city_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, help_text='Кількість ночей', verbose_name='Тривалість (ночей)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meal_type',
            field=models.CharField(choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Дворазове харчування'), ('FB', 'Триразове харчування'), ('AI', 'All Inclusive'), ('UAI', 'Ultra All Inclusive')], default='RO', max_length=3, verbose_name='Харчування'),
        ),
        migrations.AddField(
            model_name='tour',
            name='room_type',
            field=models.CharField(blank=True, default='Standard', max_length=100, verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.city', verbose_name='Курорт/місто'),
        ),
    ]
