# Generated by Django 6.0.3 on 2026-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_duration_tour_meal_type_tour_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярний готель'),
        ),
    ]
