# Generated by Django 6.0.3 on 2026-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Країна')),
                ('image', models.ImageField(upload_to='popular_destinations/', verbose_name='Фото для блоку')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Популярний напрямок',
                'verbose_name_plural': 'Популярні напрямки',
                'ordering': ['order'],
            },
        ),
    ]
