# Generated by Django 6.0.3 on 2026-04-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_populardestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='activities',
            field=models.TextField(blank=True, verbose_name='Чим зайнятися на курорті?'),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, verbose_name='Основна інформація про місто'),
        ),
        migrations.AddField(
            model_name='city',
            name='sights',
            field=models.TextField(blank=True, verbose_name='Найцікавіші визначні місця'),
        ),
    ]
