# Generated by Django 6.0.3 on 2026-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_city_activities_city_description_city_sights'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoption',
            name='adults',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Кількість дорослих'),
        ),
        migrations.AddField(
            model_name='priceoption',
            name='children_11_16',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Діти 11-16 років'),
        ),
        migrations.AddField(
            model_name='priceoption',
            name='children_2_3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Діти 2-3 роки'),
        ),
        migrations.AddField(
            model_name='priceoption',
            name='children_4_10',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Діти 4-10 років'),
        ),
        migrations.AddField(
            model_name='priceoption',
            name='infants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Діти 0-2 роки (без місця)'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за тур'),
        ),
        migrations.AlterUniqueTogether(
            name='priceoption',
            unique_together={('tour', 'departure_date', 'duration', 'departure_city', 'room_type', 'meal_type', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
        ),
    ]
