# Generated by Django 6.0.3 on 2026-04-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_priceoption_adults_priceoption_children_11_16_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceoption',
            options={'ordering': ['tour', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16'], 'verbose_name': 'Варіант ціни', 'verbose_name_plural': 'Варіанти цін'},
        ),
        migrations.AlterUniqueTogether(
            name='priceoption',
            unique_together={('tour', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='departure_city',
            field=models.CharField(blank=True, default='Кишинів', max_length=100, verbose_name='Місто вильоту'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вильоту'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кількість ночей', null=True, verbose_name='Тривалість (ночей)'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Напівпансіон'), ('FB', 'Повний пансіон'), ('AI', 'Все включено')], default='AI', max_length=50, verbose_name='Харчування'),
        ),
    ]
