# Generated by Django 6.0.3 on 2026-04-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_priceoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceoption',
            options={'ordering': ['departure_date', 'price'], 'verbose_name': 'Варіант ціни', 'verbose_name_plural': 'Варіанти цін'},
        ),
        migrations.AlterUniqueTogether(
            name='priceoption',
            unique_together={('tour', 'departure_date', 'duration', 'departure_city', 'room_type', 'meal_type', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
        ),
        migrations.CreateModel(
            name='TourPriceByTourists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Кількість дорослих')),
                ('infants', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 0-2 роки (без місця)')),
                ('children_2_3', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 2-3 роки')),
                ('children_4_10', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 4-10 років')),
                ('children_11_16', models.PositiveSmallIntegerField(default=0, verbose_name='Діти 11-16 років')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('is_default', models.BooleanField(default=False, verbose_name='Ціна за замовчуванням (якщо немає точної відповідності)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_by_tourists', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Ціна за складом туристів',
                'verbose_name_plural': 'Ціни за складом туристів',
                'unique_together': {('tour', 'adults', 'infants', 'children_2_3', 'children_4_10', 'children_11_16')},
            },
        ),
    ]
