# Generated by Django 6.0.3 on 2026-04-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_priceoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Країна')),
                ('main_text', models.TextField(blank=True, verbose_name='Основна інформація')),
                ('why_text', models.TextField(blank=True, verbose_name='Чому варто вибрати?')),
                ('popular_resorts', models.TextField(blank=True, verbose_name='Популярні курорти')),
                ('activities', models.TextField(blank=True, verbose_name='Доступні види відпочинку')),
                ('sights', models.TextField(blank=True, verbose_name="Основні визначні пам'ятки")),
                ('useful_facts', models.TextField(blank=True, verbose_name='Корисні факти для туристів')),
            ],
            options={
                'verbose_name': 'Інформація про країну',
                'verbose_name_plural': 'Інформація про країни',
            },
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country_images/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('country_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.countryinfo')),
            ],
            options={
                'verbose_name': 'Фото країни',
                'verbose_name_plural': 'Фотогалерея країни',
                'ordering': ['order'],
            },
        ),
    ]
