# Generated by Django 6.0.3 on 2026-04-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_countryinfo_countryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryImage',
        ),
    ]
