# Generated by Django 6.0.3 on 2026-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_consultation_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], default=None, null=True, verbose_name='Категорія готелю (зірки)'),
        ),
    ]
