# Generated by Django 6.0.3 on 2026-04-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_alter_tour_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecalendar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкажіть ціну в гривнях (наприклад: 15000.00). Залиште порожнім, якщо немає пропозиції', max_digits=10, null=True, verbose_name='Ціна (грн)'),
        ),
    ]
