# Generated by Django 6.0.3 on 2026-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_alter_pricecalendar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Категорія (зірки)'),
        ),
    ]
