# Generated by Django 6.0.3 on 2026-04-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_alter_tour_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
