# Generated by Django 6.0.3 on 2026-04-28 22:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото туру'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], default=None, help_text='Виберіть категорію готелю', null=True, verbose_name='Категорія готелю (зірки)'),
        ),
    ]
