# Generated by Django 6.0.3 on 2026-05-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_alter_tour_image_alter_tour_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
    ]
