# Generated by Django 6.0.3 on 2026-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_alter_booking_options_alter_booking_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
