# Generated by Django 6.0.3 on 2026-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_consultation_email_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50, verbose_name='ID готелю')),
                ('oid', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID туру')),
                ('guest_name', models.CharField(max_length=100, verbose_name="Ім'я гостя")),
                ('rating', models.IntegerField(help_text='Оцінка від 1 до 5', verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Відгук про готель',
                'verbose_name_plural': 'Відгуки про готелі',
                'ordering': ['-created_at'],
                'unique_together': {('hid', 'guest_name')},
            },
        ),
    ]
