# Generated by Django 6.0.3 on 2026-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_hotelreview_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_hid', models.CharField(db_index=True, max_length=50)),
                ('tour_oid', models.CharField(db_index=True, max_length=100)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tour_hid', 'tour_oid'], name='tours_tourv_tour_hi_58926a_idx'), models.Index(fields=['visited_at'], name='tours_tourv_visited_8be957_idx')],
            },
        ),
    ]
