# Generated by Django 6.0.3 on 2026-05-15 14:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_tourvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50, verbose_name='ID готелю (hid)')),
                ('oid', models.CharField(max_length=100, verbose_name='ID пропозиції (oid)')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Назва готелю')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто/курорт')),
                ('rating', models.FloatField(default=8.0, verbose_name='Рейтинг (0-10)')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кількість відгуків')),
                ('price', models.IntegerField(verbose_name='Ціна за тур (грн)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото готелю')),
                ('image_url', models.URLField(blank=True, verbose_name='URL фото (якщо немає завантаженого)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Популярний готель',
                'verbose_name_plural': 'Популярні готелі',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
