# Generated by Django 6.0.3 on 2026-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_popularhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularhotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popular_hotels/', verbose_name='Фото готелю'),
        ),
    ]
