# Generated by Django 6.0.3 on 2026-05-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_alter_popularhotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularhotel',
            name='od',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дата вильоту'),
        ),
        migrations.AddField(
            model_name='popularhotel',
            name='ol',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Тривалість (ночей)'),
        ),
    ]
