# Generated by Django 6.0.3 on 2026-04-14 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Лише малі літери, цифри та дефіс')], verbose_name='Адреса сайту')),
                ('hero_title', models.CharField(default='Ваша подорож починається тут', max_length=200)),
                ('hero_subtitle', models.CharField(default='Знайдіть ідеальний тур за лічені хвилини', max_length=200)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='agent_hero/', verbose_name='Фонова картинка (рекомендовано 1200x400px)')),
                ('top_logo', models.ImageField(blank=True, null=True, upload_to='agent_logos/', verbose_name='Верхній логотип (250x250px)')),
                ('bottom_logo', models.ImageField(blank=True, null=True, upload_to='agent_logos/', verbose_name='Нижній логотип (150x150px або 150x50px)')),
                ('enlarge_logo', models.BooleanField(default=False, verbose_name='Збільшити логотип на 25%')),
                ('show_news', models.BooleanField(default=True, verbose_name='Показувати новини')),
                ('show_operator_logos', models.BooleanField(default=False, verbose_name='Відображати логотипи туроператорів на сайті при пошуку турів')),
                ('agency_name', models.CharField(blank=True, max_length=200, verbose_name='Назва турагенції')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_site', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
