# Generated by Django 6.0.3 on 2026-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='create_own_tours',
            field=models.BooleanField(default=False, verbose_name='Створювати власні тури'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='use_superadmin_tours',
            field=models.BooleanField(default=False, verbose_name='Використовувати тури суперадміна'),
        ),
    ]
