# Generated by Django 6.0.3 on 2026-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_agentsite_create_own_tours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsite',
            name='create_own_tours',
        ),
        migrations.RemoveField(
            model_name='agentsite',
            name='use_superadmin_tours',
        ),
        migrations.AddField(
            model_name='agentsite',
            name='show_superadmin_tours',
            field=models.BooleanField(default=False, verbose_name='Показувати тури суперадміна'),
        ),
    ]
