# Generated by Django 6.0.3 on 2026-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_remove_agentsite_create_own_tours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='primary_color',
            field=models.CharField(default='#086745', help_text='Введіть HEX-код кольору, наприклад #086745', max_length=7, verbose_name='Головний колір сайту'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='secondary_color',
            field=models.CharField(blank=True, default='#2a6b5c', max_length=7, verbose_name='Додатковий колір'),
        ),
    ]
