# Generated by Django 6.0.3 on 2026-04-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_agentsite_primary_color_agentsite_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsite',
            name='primary_color',
            field=models.CharField(default='#086745', help_text='Колір для кнопок, посилань та акцентів. Введіть HEX-код, наприклад #086745', max_length=7, verbose_name='Головний колір'),
        ),
        migrations.AlterField(
            model_name='agentsite',
            name='secondary_color',
            field=models.CharField(default='#02432c', help_text='Колір для hover-ефектів. Введіть HEX-код, наприклад #02432c', max_length=7, verbose_name='Додатковий колір'),
        ),
    ]
