# Generated by Django 6.0.3 on 2026-04-28 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_create_agentsite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks_order', models.JSONField(default=list, help_text='Порядок блоків на сторінці (тільки ті, які можна переставляти)')),
                ('active_blocks', models.JSONField(default=list, help_text='Які блоки активні (показуються на сайті)')),
                ('banners', models.JSONField(default=list, help_text="[{'image': 'url', 'link': 'url', 'position': 'full', 'order': 1, 'title': 'Назва банера'}]")),
                ('custom_css', models.TextField(blank=True, help_text='Додатковий CSS')),
                ('custom_js', models.TextField(blank=True, help_text='Додатковий JavaScript')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='block_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування блоків агента',
                'verbose_name_plural': 'Налаштування блоків агентів',
            },
        ),
    ]
