# Generated by Django 6.0.3 on 2026-04-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_agentblocksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name="Фото для блоку 'Про нас'"),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='about_us_text',
            field=models.TextField(default='Ми – команда професіоналів, яка допомагає втілювати ваші мрії про подорожі в реальність. З понад 10-річним досвідом у туризмі, ми пропонуємо лише перевірені тури, найкращі ціни та індивідуальний підхід до кожного клієнта.', verbose_name="Текст блоку 'Про нас'"),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='about_us_title',
            field=models.CharField(default='Про нас', max_length=200, verbose_name="Заголовок блоку 'Про нас'"),
        ),
        migrations.AlterField(
            model_name='agentblocksettings',
            name='active_blocks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='agentblocksettings',
            name='banners',
            field=models.JSONField(default=list, help_text="[{'image': 'url', 'link': 'url', 'position': 'full', 'title': 'Назва банера', 'order': 1, 'active': True, 'overlay_opacity': 0.4, 'text_blocks': [{'id': '1', 'heading': 'Заголовок', 'text': 'Текст', 'position': 'center', 'heading_color': '#ffffff', 'text_color': '#ffffff', 'button_text': 'Детальніше', 'button_color': '#086745', 'button_link': 'https://...'}]}]"),
        ),
        migrations.AlterField(
            model_name='agentblocksettings',
            name='blocks_order',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='agentblocksettings',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentblocksettings',
            name='custom_js',
            field=models.TextField(blank=True),
        ),
    ]
