# Generated by Django 6.0.3 on 2026-04-29 11:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_agentsite_about_us_image_agentsite_about_us_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsite',
            name='hero_background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_background'),
        ),
    ]
