# Generated by Django 6.0.3 on 2026-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_alter_agentsite_hero_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 32×32px, 64×64px або 128×128px. Формати: PNG, ICO, SVG, GIF', null=True, upload_to='agent_favicons/', verbose_name='Іконка сайту (favicon)'),
        ),
    ]
