# Generated by Django 6.0.3 on 2026-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_agentsite_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='hide_logo',
            field=models.BooleanField(default=False, help_text='Якщо увімкнути, логотип не відображатиметься на сайті (ні свій, ні наш)', verbose_name='Без логотипу (немає логотипу)'),
        ),
    ]
