# Generated by Django 6.0.3 on 2026-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_agentsite_hide_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Посилання на Facebook сторінку', null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Посилання на Instagram', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_telegram',
            field=models.URLField(blank=True, help_text='Посилання на Telegram канал або чат', null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_tiktok',
            field=models.URLField(blank=True, help_text='Посилання на TikTok', null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='Посилання на YouTube канал', null=True, verbose_name='YouTube'),
        ),
    ]
