# Generated by Django 6.0.3 on 2026-10-05 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_agentsite_social_facebook_agentsite_social_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsite',
            name='footer_address',
            field=models.CharField(blank=True, default='', help_text='Адреса для відображення у футері (наприклад: м. Київ, вул. Хрещатик, 1)', max_length=255, verbose_name='Адреса офісу у футері'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='footer_email',
            field=models.EmailField(blank=True, default='', help_text='Email для відображення у футері', max_length=100, verbose_name='Email у футері'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='footer_phone',
            field=models.CharField(blank=True, default='', help_text='Номер телефону для відображення у футері (наприклад: +38 (099) 123-45-67)', max_length=20, verbose_name='Телефон у футері'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='footer_show_contact',
            field=models.BooleanField(default=True, help_text='Відображати блок з контактною інформацією у футері', verbose_name='Показувати контакти у футері'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='managers',
            field=models.JSONField(blank=True, default=list, help_text='Список менеджерів у форматі JSON', verbose_name='Менеджери'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_discord',
            field=models.URLField(blank=True, help_text='Посилання на Discord', null=True, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='Посилання на LinkedIn', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_pinterest',
            field=models.URLField(blank=True, help_text='Посилання на Pinterest', null=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_signal',
            field=models.URLField(blank=True, help_text='Посилання на Signal', null=True, verbose_name='Signal'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_snapchat',
            field=models.URLField(blank=True, help_text='Посилання на Snapchat', null=True, verbose_name='Snapchat'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_threads',
            field=models.URLField(blank=True, help_text='Посилання на Threads', null=True, verbose_name='Threads'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_twitch',
            field=models.URLField(blank=True, help_text='Посилання на Twitch', null=True, verbose_name='Twitch'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_viber',
            field=models.URLField(blank=True, help_text='Посилання на Viber (наприклад: viber://chat?number=380991234567)', null=True, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_whatsapp',
            field=models.URLField(blank=True, help_text='Посилання на WhatsApp (наприклад: https://wa.me/380991234567)', null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='social_x',
            field=models.URLField(blank=True, help_text='Посилання на X/Twitter', null=True, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='agentsite',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Отримайте у бота @userinfobot. Якщо не вказано - сповіщення не будуть приходити в Telegram.', max_length=50, null=True, verbose_name='Telegram Chat ID для сповіщень'),
        ),
        migrations.AlterField(
            model_name='agentsite',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$', 'Лише латинські літери (великі та малі), цифри та дефіс')], verbose_name='Адреса сайту'),
        ),
    ]
